---
# Per environment values which override defaults in hmpps-x-ray-body-scans-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: x-ray-body-scans-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENVIRONMENT: preprod
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_HMPPS_AUTH_BASE_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    API_PRISON_API_BASE_URL: "https://prison-api-preprod.prison.service.justice.gov.uk"
    API_ALERTS_API_BASE_URL: "https://alerts-api-preprod.hmpps.service.justice.gov.uk"
    API_CASE_NOTES_API_BASE_URL: "https://preprod.offender-case-notes.service.justice.gov.uk"

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '30 21 * * 1-5' # Stop at 9.30pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-connect-dps-non-prod
  businessHoursOnly: true
